spring:
  datasource:
    url: jdbc:mysql://localhost:3306/analysisengine?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mappers/*.xml